services:
  db:
    image: postgres:17
    container_name: postgres_17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BANCO_POPULADO_V2 
    volumes:
      - ./backup/dump-asdads-202509092110.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
