services:
  db:
    image: postgres:17
    container_name: postgres_db_service
    networks:
      - pardal-network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
     - pardal_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-dek:
    image: postgres:17
    container_name: postgres_db_dek
    networks:
      - vault-network
      - pardal-network
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "3159:5432"
    volumes:
      - dek_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: hashicorp/vault:1.15.6
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - vault-network

  vault-init:
    image: hashicorp/vault:1.15.6
    container_name: vault-init
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root-token
    depends_on:
      vault:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c "
      echo 'Aguardando Vault estar pronto...';
      sleep 2;

      echo 'Habilitando Transit Engine...';
      vault secrets enable transit || echo 'Transit já habilitado';

      echo 'Criando chave de criptografia user-encryption-key...';
      vault write -f transit/keys/user-encryption-key || echo 'Chave já existe';

      echo 'Configurando políticas de acesso...';
      vault policy write transit-policy - <<EOF
      path \"transit/encrypt/user-encryption-key\" {
        capabilities = [\"update\"]
      }
      path \"transit/decrypt/user-encryption-key\" {
        capabilities = [\"update\"]
      }
      EOF

      echo 'Vault configurado com sucesso!';
      "
    networks:
      - vault-network
    restart: "no"


  mongo:
    image: mongo:8
    container_name: mongo_audit_service
    networks:
      - pardal-network
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  etl-restore-watcher:
    build:
      context: ./etl-python
    networks:
      - pardal-network
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./restore:/app/restore
      - ./restore_status:/app/restore_status
      - ./dump_processed:/app/dump_processed
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

    command: /bin/bash /app/config/restore-watcher.sh


  etl-service:
    build:
      context: ./etl-python
    networks:
      - pardal-network
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./dump:/app/dump
      - ./restore_status:/app/restore_status
      - ./etl-python/data:/app/output/insights_data
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

    command: python -u main.py

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  vault-pg-data:
    driver: local
  mongo-data:
  pardal_db_data:
  dek_db_data:
networks:
  pardal-network:
    driver: bridge
  vault-network:
    driver: bridge