CREATE SCHEMA voucher
CREATE TABLE data_encryption_key
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_dek     VARCHAR(255),
    email_dek    VARCHAR(255),
    phone_dek    VARCHAR(255),
    reference_id VARCHAR(255),
    CONSTRAINT pk_data_encryption_key PRIMARY KEY (id)
);